name: NativeCommon - Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  win_build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          python -m venv venv --clear
          .\venv\Scripts\activate
          pip install conan --upgrade
          conan remove -c "*"
          conan remote add --index 0 art ${{ secrets.CONAN_REPO_URL }} || true

      - name: Build and Test
        run: |
          call vcvars32
          if exist build\ rmdir /s /q build || exit /b 1
          mkdir build || exit /b 1
          cd build || exit /b 1
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG=/MT -DCMAKE_CXX_FLAGS_DEBUG=/MT -G Ninja ..
          cmake --build . --target tests || exit /b 1
          ctest -D ExperimentalTest --no-compress-output || exit /b 1

      - name: Upload Built Binaries
        run: |
          call .\venv\Scripts\activate
          conan remote login art "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_PASSWORD }}"
          conan upload -r art -c "*" > upload.txt 2>&1
          conan remove -c "*"

  linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Conan and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          python3 -m pip install conan --upgrade
          conan remote add --index 0 art ${{ secrets.CONAN_REPO_URL }} || true

      - name: Build and Test
        run: |
          set -x -e
          conan remove -c "*"
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DSANITIZE=yes ..
          ninja tests
          ctest -D ExperimentalTest --no-compress-output

      - name: Upload Built Binaries
        run: |
          conan remote login art "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_PASSWORD }}"
          conan upload -r art -c "*" 1>&2
          conan remove -c "*"

  mac_build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Conan and Ninja
        run: |
          python3 -m venv venv
          source ./venv/bin/activate
          python3 -m pip install conan
          conan remove -c "*"
          conan remote add --index 0 art ${{ secrets.CONAN_REPO_URL }} || true
          brew install ninja

      - name: Build and Test
        run: |
          set -x -e
          PROJECT_PATH=$(pwd)
          ARCH=$(uname -m)
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_OSX_ARCHITECTURES="$ARCH" ..
          ninja tests
          ctest -D ExperimentalTest --no-compress-output

      - name: Upload Built Binaries
        run: |
          source ./venv/bin/activate
          conan remote login art "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_PASSWORD }}"
          conan upload -r art -c "*" 1>&2
          conan remove -c "*"
          rm -rf venv
