name: conan-recipes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Conan
        run: |
          pip install conan==2.7.0

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=conan2

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest
